"""
Django settings for example project.

Generated by Cookiecutter Django Package
"""

import os
import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve(strict=True).parent.parent


sys.path.append(str(BASE_DIR / "tests"))

SECRET_KEY = "=bodvqgkt@)emfe2!($i#1zd(x27@u!9*9+)^$8bu#sqsmm^*n"

DEBUG = True

ALLOWED_HOSTS = ["*"]

INSTALLED_APPS = [
    "easy_icons",
    "example",
]


ROOT_URLCONF = "example.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
            ],
        },
    },
]

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}

# Configuration for the new API
EASY_ICONS = {
    # Default SVG renderer configuration
    "default": {
        "renderer": "easy_icons.renderers.SvgRenderer",
        "config": {
            "svg_dir": "icons",
            "default_attrs": {
                "height": "1em",
                "fill": "currentColor",
            },
        },
        # Example: Load icon packs from third-party packages or your own modules
        # Packs are merged in order (last wins), then explicit icons override all
        "packs": [
            "example.icons.SVG",  # Load icons from example.icons.SVG dict
        ],
        "icons": {
            "home": "home.svg",
            "user": "user.svg",
            "star": "star.svg",
            "alt_dir": "../alt_dir/alt_dir.svg",  # Custom path example
        },
    },
    # Font Awesome provider renderer
    "fontawesome": {
        "renderer": "easy_icons.renderers.ProviderRenderer",
        "config": {
            "tag": "i",
            "default_attrs": {"class": "fas"},
        },
        # Load FontAwesome icon pack
        "packs": [
            "example.icons.FONTAWESOME",
        ],
        "icons": {
            "heart": "fa-heart",
            "star": "fa-star",
            "admin": "fa-toolbox",
            "user": "fa-user",
            "cog": "fa-cog",
        },
    },
    # SVG sprite renderer example (for demonstration)
    "sprites": {
        "renderer": "easy_icons.renderers.SpritesRenderer",
        "config": {
            "sprite_path": "sprites/icons.svg",
            "default_attrs": {"class": "icon"},
        },
        "icons": {
            "logo": "company-logo",
            "menu": "hamburger-menu",
            "search": "search-icon",
        },
    },
}
